// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwrcctrisqeqnhwhbosy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cmNjdHJpc3FlcW5od2hib3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTg5NTMsImV4cCI6MjA2Nzk5NDk1M30.xJHAzHgW0pfImPRXkPur8zXH1Fia9eCtVklHyYUQMo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});